name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm -F sizuku deps

      - name: Check
        run: pnpm check
      
      - name: Typecheck
        run: pnpm -F sizuku typecheck

      - name: Build
        run: pnpm -F sizuku build

      - name: Run Coverage
        run: pnpm -F sizuku coverage